// Clasificación Industrial Internacional Uniforme (CIIU Rev 4 A.C. / DIAN Colombia - 503 clases)
window.CIIU_DATA = [
  // SECCIÓN A - AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA
  { code: "0111", name: "0111 - Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas" },
  { code: "0112", name: "0112 - Cultivo de arroz" },
  { code: "0113", name: "0113 - Cultivo de hortalizas, raíces y tubérculos" },
  { code: "0114", name: "0114 - Cultivo de caña de azúcar" },
  { code: "0115", name: "0115 - Cultivo de tabaco" },
  { code: "0119", name: "0119 - Otros cultivos no perennes" },
  { code: "0121", name: "0121 - Cultivo de frutas tropicales y subtropicales" },
  { code: "0122", name: "0122 - Cultivo de plátano y banano" },
  { code: "0123", name: "0123 - Cultivo de frutas cítricas" },
  { code: "0124", name: "0124 - Cultivo de frutas de pepita y de hueso" },
  { code: "0125", name: "0125 - Cultivo de otros frutos y nueces de árboles y arbustos" },
  { code: "0126", name: "0126 - Cultivo de frutos oleaginosos" },
  { code: "0127", name: "0127 - Cultivo de plantas con las que se preparan bebidas (café, cacao, té)" },
  { code: "0128", name: "0128 - Cultivo de especias y de plantas aromáticas, medicinales y farmacéuticas" },
  { code: "0129", name: "0129 - Otros cultivos perennes" },
  { code: "0130", name: "0130 - Propagación de plantas (viveros)" },
  { code: "0141", name: "0141 - Cría de ganado bovino y bubalino" },
  { code: "0142", name: "0142 - Cría de caballos y otros equinos" },
  { code: "0143", name: "0143 - Cría de camélidos y otros equinos especiales" },
  { code: "0144", name: "0144 - Cría de ganado ovino y caprino" },
  { code: "0145", name: "0145 - Cría de ganado porcino" },
  { code: "0146", name: "0146 - Cría de aves de corral" },
  { code: "0149", name: "0149 - Cría de otros animales" },
  { code: "0150", name: "0150 - Explotación mixta (agrícola y pecuaria)" },
  { code: "0161", name: "0161 - Actividades de apoyo a la agricultura" },
  { code: "0162", name: "0162 - Actividades de apoyo a la ganadería" },
  { code: "0163", name: "0163 - Actividades posteriores a la cosecha" },
  { code: "0164", name: "0164 - Tratamiento de semillas para propagación" },
  { code: "0170", name: "0170 - Caza ordinaria y mediante trampas y actividades de servicios conexas" },
  { code: "0210", name: "0210 - Silvicultura y otras actividades forestales" },
  { code: "0220", name: "0220 - Extracción de madera" },
  { code: "0230", name: "0230 - Recolección de productos forestales distintos de la madera" },
  { code: "0240", name: "0240 - Servicios de apoyo a la silvicultura" },
  { code: "0311", name: "0311 - Pesca marítima" },
  { code: "0312", name: "0312 - Pesca de agua dulce" },
  { code: "0321", name: "0321 - Acuicultura marítima" },
  { code: "0322", name: "0322 - Acuicultura de agua dulce" },

  // SECCIÓN B - EXPLOTACIÓN DE MINAS Y CANTERAS
  { code: "0510", name: "0510 - Extracción de hulla (carbón de piedra)" },
  { code: "0520", name: "0520 - Extracción de carbón lignito" },
  { code: "0610", name: "0610 - Extracción de petróleo crudo" },
  { code: "0620", name: "0620 - Extracción de gas natural" },
  { code: "0710", name: "0710 - Extracción de minerales de hierro" },
  { code: "0721", name: "0721 - Extracción de minerales de uranio y torio" },
  { code: "0722", name: "0722 - Extracción de oro y otros metales preciosos" },
  { code: "0723", name: "0723 - Extracción de minerales de níquel" },
  { code: "0729", name: "0729 - Extracción de otros minerales metalíferos no ferrosos" },
  { code: "0811", name: "0811 - Extracción de piedra, arena, arcillas comunes, yeso y caliza" },
  { code: "0812", name: "0812 - Extracción de grava, silicio y esmeraldas" },
  { code: "0891", name: "0891 - Extracción de minerales para la fabricación de abonos y productos químicos" },
  { code: "0892", name: "0892 - Extracción de turba" },
  { code: "0899", name: "0899 - Extracción de otros minerales no metálicos n.c.p." },
  { code: "0910", name: "0910 - Actividades de apoyo para la extracción de petróleo y gas natural" },
  { code: "0990", name: "0990 - Actividades de apoyo para otras actividades de explotación de minas y canteras" },

  // SECCIÓN C - INDUSTRIAS MANUFACTURERAS
  { code: "1011", name: "1011 - Procesamiento y conservación de carne y productos cárnicos" },
  { code: "1012", name: "1012 - Procesamiento y conservación de pescados, crustáceos y moluscos" },
  { code: "1020", name: "1020 - Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos" },
  { code: "1030", name: "1030 - Elaboración de aceites y grasas de origen vegetal y animal" },
  { code: "1040", name: "1040 - Elaboración de productos lácteos" },
  { code: "1051", name: "1051 - Elaboración de productos de molinería" },
  { code: "1052", name: "1052 - Elaboración de almidones y productos derivados del almidón" },
  { code: "1061", name: "1061 - Trilla de café" },
  { code: "1062", name: "1062 - Descafeinado, tostación y molienda del café" },
  { code: "1063", name: "1063 - Elaboración de otros derivados del café" },
  { code: "1071", name: "1071 - Elaboración de panela" },
  { code: "1072", name: "1072 - Elaboración de azúcar" },
  { code: "1081", name: "1081 - Elaboración de productos de panadería" },
  { code: "1082", name: "1082 - Elaboración de cacao, chocolate y confitería" },
  { code: "1083", name: "1083 - Elaboración de pastas, fideos, cuscús y productos farináceos similares" },
  { code: "1084", name: "1084 - Elaboración de comidas y platos preparados" },
  { code: "1089", name: "1089 - Elaboración de otros productos alimenticios n.c.p." },
  { code: "1090", name: "1090 - Elaboración de alimentos preparados para animales" },
  { code: "1101", name: "1101 - Destilación, rectificación y mezcla de bebidas alcohólicas" },
  { code: "1102", name: "1102 - Elaboración de bebidas fermentadas no destiladas (vinos)" },
  { code: "1103", name: "1103 - Elaboración de cerveza y otras bebidas malteadas" },
  { code: "1104", name: "1104 - Elaboración de bebidas no alcohólicas, producción de aguas minerales" },
  { code: "1200", name: "1200 - Elaboración de productos de tabaco" },
  { code: "1311", name: "1311 - Preparación e hilatura de fibras textiles" },
  { code: "1312", name: "1312 - Tejedura de productos textiles" },
  { code: "1313", name: "1313 - Acabado de productos textiles" },
  { code: "1391", name: "1391 - Fabricación de tejidos de punto y ganchillo" },
  { code: "1392", name: "1392 - Fabricación de artículos confeccionados de material textil, excepto prendas de vestir" },
  { code: "1393", name: "1393 - Fabricación de tapices y alfombras" },
  { code: "1394", name: "1394 - Fabricación de cuerdas, cordeles, bramantes y redes" },
  { code: "1399", name: "1399 - Fabricación de otros productos textiles n.c.p." },
  { code: "1410", name: "1410 - Confección de prendas de vestir, excepto prendas de piel" },
  { code: "1420", name: "1420 - Fabricación de artículos de piel" },
  { code: "1430", name: "1430 - Fabricación de artículos de punto y ganchillo" },
  { code: "1511", name: "1511 - Curtido y adobo de cueros; adobo y teñido de pieles" },
  { code: "1512", name: "1512 - Fabricación de maletas, bolsos de mano y artículos similares, y marroquinería" },
  { code: "1521", name: "1521 - Fabricación de calzado de cuero y piel" },
  { code: "1522", name: "1522 - Fabricación de otros tipos de calzado, excepto calzado de cuero y piel" },
  { code: "1523", name: "1523 - Fabricación de partes de calzado" },
  { code: "1610", name: "1610 - Aserrado, acepillado e impregnación de la madera" },
  { code: "1620", name: "1620 - Fabricación de hojas de madera para enchapado y tableros a base de madera" },
  { code: "1630", name: "1630 - Fabricación de partes y piezas de madera para la construcción" },
  { code: "1640", name: "1640 - Fabricación de recipientes de madera" },
  { code: "1690", name: "1690 - Fabricación de otros productos de madera, corcho, paja y materiales trenzables" },
  { code: "1701", name: "1701 - Fabricación de pastas celulósicas, papel y cartón" },
  { code: "1702", name: "1702 - Fabricación de papel y cartón ondulado, envases de papel y cartón" },
  { code: "1709", name: "1709 - Fabricación de otros artículos de papel y cartón" },
  { code: "1811", name: "1811 - Impresión" },
  { code: "1812", name: "1812 - Actividades de servicios relacionados con la impresión" },
  { code: "1820", name: "1820 - Reproducción de grabaciones" },
  { code: "1910", name: "1910 - Fabricación de productos de hornos de coque" },
  { code: "1921", name: "1921 - Fabricación de productos de la refinación del petróleo" },
  { code: "1922", name: "1922 - Mezcla de combustibles elaborados" },
  { code: "2011", name: "2011 - Fabricación de sustancias químicas básicas" },
  { code: "2012", name: "2012 - Fabricación de abonos y compuestos inorgánicos nitrogenados" },
  { code: "2013", name: "2013 - Fabricación de plásticos y caucho sintético en formas primarias" },
  { code: "2021", name: "2021 - Fabricación de plaguicidas y otros productos químicos de uso agropecuario" },
  { code: "2022", name: "2022 - Fabricación de pinturas, barnices, tintas de imprenta y masillas" },
  { code: "2023", name: "2023 - Fabricación de jabones, detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador" },
  { code: "2029", name: "2029 - Fabricación de otros productos químicos n.c.p." },
  { code: "2030", name: "2030 - Fabricación de fibras sintéticas y artificiales" },
  { code: "2100", name: "2100 - Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos" },
  { code: "2211", name: "2211 - Fabricación de llantas y neumáticos de caucho" },
  { code: "2212", name: "2212 - Reencauche de llantas de caucho" },
  { code: "2219", name: "2219 - Fabricación de otros productos de caucho" },
  { code: "2221", name: "2221 - Fabricación de formas plásticas en formas primarias" },
  { code: "2229", name: "2229 - Fabricación de artículos de plástico n.c.p." },
  { code: "2310", name: "2310 - Fabricación de vidrio y productos de vidrio" },
  { code: "2391", name: "2391 - Fabricación de productos refractarios" },
  { code: "2392", name: "2392 - Fabricación de materiales de arcilla para la construcción" },
  { code: "2393", name: "2393 - Fabricación de otros productos de cerámica y porcelana" },
  { code: "2394", name: "2394 - Fabricación de cemento, cal y yeso" },
  { code: "2395", name: "2395 - Fabricación de artículos de hormigón, cemento y yeso" },
  { code: "2396", name: "2396 - Corte, tallado y acabado de la piedra" },
  { code: "2399", name: "2399 - Fabricación de otros productos minerales no metálicos n.c.p." },
  { code: "2410", name: "2410 - Industrias básicas de hierro y de acero" },
  { code: "2421", name: "2421 - Industrias básicas de metales preciosos" },
  { code: "2429", name: "2429 - Industrias básicas de otros metales no ferrosos" },
  { code: "2431", name: "2431 - Fundición de hierro y de acero" },
  { code: "2432", name: "2432 - Fundición de metales no ferrosos" },
  { code: "2511", name: "2511 - Fabricación de productos metálicos para uso estructural" },
  { code: "2512", name: "2512 - Fabricación de tanques, depósitos y recipientes de metal" },
  { code: "2513", name: "2513 - Fabricación de generadores de vapor, excepto calderas de agua caliente" },
  { code: "2520", name: "2520 - Fabricación de armas y municiones" },
  { code: "2591", name: "2591 - Forja, prensado, estampado y laminado de metales; pulvimetalurgia" },
  { code: "2592", name: "2592 - Tratamiento y revestimiento de metales; mecanizado" },
  { code: "2593", name: "2593 - Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería" },
  { code: "2599", name: "2599 - Fabricación de otros productos elaborados de metal n.c.p." },
  { code: "2610", name: "2610 - Fabricación de componentes y tableros electrónicos" },
  { code: "2620", name: "2620 - Fabricación de computadores y equipo periférico" },
  { code: "2630", name: "2630 - Fabricación de equipos de comunicación" },
  { code: "2640", name: "2640 - Fabricación de aparatos electrónicos de consumo" },
  { code: "2651", name: "2651 - Fabricación de equipo de medición, prueba, navegación y control" },
  { code: "2652", name: "2652 - Fabricación de relojes" },
  { code: "2660", name: "2660 - Fabricación de equipo de irradiación, médico y electroterapéutico" },
  { code: "2670", name: "2670 - Fabricación de instrumentos ópticos y equipo fotográfico" },
  { code: "2680", name: "2680 - Fabricación de soportes magnéticos y ópticos impresos" },
  { code: "2711", name: "2711 - Fabricación de motores, generadores y transformadores eléctricos" },
  { code: "2712", name: "2712 - Fabricación de aparatos de distribución y control de la energía eléctrica" },
  { code: "2720", name: "2720 - Fabricación de pilas, baterías y acumuladores eléctricos" },
  { code: "2731", name: "2731 - Fabricación de cables de fibra óptica" },
  { code: "2732", name: "2732 - Fabricación de otros hilos y cables eléctricos" },
  { code: "2740", name: "2740 - Fabricación de equipos de iluminación" },
  { code: "2750", name: "2750 - Fabricación de aparatos de uso doméstico" },
  { code: "2790", name: "2790 - Fabricación de otros tipos de equipo eléctrico n.c.p." },
  { code: "2811", name: "2811 - Fabricación de motores y turbinas, excepto motores para aeronaves y vehículos" },
  { code: "2812", name: "2812 - Fabricación de equipos de potencia hidráulica y neumática" },
  { code: "2813", name: "2813 - Fabricación de otras bombas, compresores, grifos y válvulas" },
  { code: "2814", name: "2814 - Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión" },
  { code: "2815", name: "2815 - Fabricación de hornos, hogares y quemadores industriales" },
  { code: "2816", name: "2816 - Fabricación de equipo de elevación y manipulación" },
  { code: "2817", name: "2817 - Fabricación de maquinaria y equipo de oficina (excepto computadores)" },
  { code: "2818", name: "2818 - Fabricación de herramientas mecánicas manuales" },
  { code: "2819", name: "2819 - Fabricación de otros tipos de maquinaria de uso general" },
  { code: "2821", name: "2821 - Fabricación de maquinaria agropecuaria y forestal" },
  { code: "2822", name: "2822 - Fabricación de máquinas formadoras de metal y de máquinas herramienta" },
  { code: "2823", name: "2823 - Fabricación de maquinaria para la metalurgia" },
  { code: "2824", name: "2824 - Fabricación de maquinaria para la explotación de minas y canteras" },
  { code: "2825", name: "2825 - Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco" },
  { code: "2826", name: "2826 - Fabricación de maquinaria para la elaboración de textiles, prendas de vestir y cueros" },
  { code: "2829", name: "2829 - Fabricación de otros tipos de maquinaria de uso especial" },
  { code: "2910", name: "2910 - Fabricación de vehículos automotores y sus motores" },
  { code: "2920", name: "2920 - Fabricación de carrocerías para vehículos automotores; remolques" },
  { code: "2930", name: "2930 - Fabricación de partes, piezas y accesorios para vehículos automotores" },
  { code: "3011", name: "3011 - Construcción de barcos y estructuras flotantes" },
  { code: "3012", name: "3012 - Construcción de embarcaciones de recreo y deporte" },
  { code: "3020", name: "3020 - Fabricación de locomotoras y de material rodante para ferrocarriles" },
  { code: "3030", name: "3030 - Fabricación de aeronaves, naves espaciales y maquinaria conexa" },
  { code: "3040", name: "3040 - Fabricación de vehículos militares de combate" },
  { code: "3091", name: "3091 - Fabricación de motocicletas" },
  { code: "3092", name: "3092 - Fabricación de bicicletas y de sillones de ruedas para personas con discapacidad" },
  { code: "3099", name: "3099 - Fabricación de otros tipos de equipo de transporte n.c.p." },
  { code: "3110", name: "3110 - Fabricación de muebles" },
  { code: "3120", name: "3120 - Fabricación de colchones y somieres" },
  { code: "3211", name: "3211 - Fabricación de joyas y artículos conexos" },
  { code: "3212", name: "3212 - Fabricación de bisutería y artículos conexos" },
  { code: "3220", name: "3220 - Fabricación de instrumentos musicales" },
  { code: "3230", name: "3230 - Fabricación de artículos de deporte" },
  { code: "3240", name: "3240 - Fabricación de juegos, juguetes y rompecabezas" },
  { code: "3250", name: "3250 - Fabricación de instrumentos, aparatos y materiales médicos y odontológicos" },
  { code: "3290", name: "3290 - Otras industrias manufactureras n.c.p." },
  { code: "3311", name: "3311 - Mantenimiento y reparación especializado de productos elaborados en metal" },
  { code: "3312", name: "3312 - Mantenimiento y reparación especializado de maquinaria y equipo" },
  { code: "3313", name: "3313 - Mantenimiento y reparación especializado de equipo electrónico y óptico" },
  { code: "3314", name: "3314 - Mantenimiento y reparación especializado de equipo eléctrico" },
  { code: "3315", name: "3315 - Mantenimiento y reparación especializado de equipo de transporte, excepto vehículos" },
  { code: "3319", name: "3319 - Mantenimiento y reparación de otros tipos de equipos" },
  { code: "3320", name: "3320 - Instalación especializada de maquinaria y equipo industrial" },

  // SECCIÓN D - SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO
  { code: "3511", name: "3511 - Generación de energía eléctrica" },
  { code: "3512", name: "3512 - Transmisión de energía eléctrica" },
  { code: "3513", name: "3513 - Distribución de energía eléctrica" },
  { code: "3514", name: "3514 - Comercialización de energía eléctrica" },
  { code: "3520", name: "3520 - Producción de gas; distribución de combustibles gaseosos por tubería" },
  { code: "3530", name: "3530 - Suministro de vapor y aire acondicionado" },

  // SECCIÓN E - AGUA, ALCANTARILLADO, GESTIÓN DE DESECHOS Y SANEAMIENTO
  { code: "3600", name: "3600 - Captación, tratamiento y distribución de agua" },
  { code: "3700", name: "3700 - Evacuación y tratamiento de aguas residuales" },
  { code: "3811", name: "3811 - Recolección de desechos no peligrosos" },
  { code: "3812", name: "3812 - Recolección de desechos peligrosos" },
  { code: "3821", name: "3821 - Tratamiento y disposición de desechos no peligrosos" },
  { code: "3822", name: "3822 - Tratamiento y disposición de desechos peligrosos" },
  { code: "3830", name: "3830 - Recuperación de materiales" },
  { code: "3900", name: "3900 - Actividades de saneamiento ambiental y otros servicios de gestión de desechos" },

  // SECCIÓN F - CONSTRUCCIÓN
  { code: "4111", name: "4111 - Construcción de edificios residenciales" },
  { code: "4112", name: "4112 - Construcción de edificios no residenciales" },
  { code: "4210", name: "4210 - Construcción de carreteras y vías de ferrocarril" },
  { code: "4220", name: "4220 - Construcción de proyectos de servicio público" },
  { code: "4290", name: "4290 - Construcción de otras obras de ingeniería civil" },
  { code: "4311", name: "4311 - Demolición" },
  { code: "4312", name: "4312 - Preparación del terreno" },
  { code: "4321", name: "4321 - Instalaciones eléctricas" },
  { code: "4322", name: "4322 - Instalaciones de fontanería, calefacción y aire acondicionado" },
  { code: "4329", name: "4329 - Otras instalaciones para obras de construcción" },
  { code: "4330", name: "4330 - Terminación y acabado de edificios y obras de ingeniería civil" },
  { code: "4390", name: "4390 - Otras actividades especializadas de construcción" },

  // SECCIÓN G - COMERCIO AL POR MAYOR Y AL POR MENOR
  { code: "4511", name: "4511 - Comercio de vehículos automotores nuevos" },
  { code: "4512", name: "4512 - Comercio de vehículos automotores usados" },
  { code: "4520", name: "4520 - Mantenimiento y reparación de vehículos automotores" },
  { code: "4530", name: "4530 - Comercio de partes, piezas y accesorios para vehículos automotores" },
  { code: "4541", name: "4541 - Comercio de motocicletas y de sus partes, piezas y accesorios" },
  { code: "4542", name: "4542 - Mantenimiento y reparación de motocicletas y de sus partes y piezas" },
  { code: "4610", name: "4610 - Comercio al por mayor a cambio de una retribución o por contrata" },
  { code: "4620", name: "4620 - Comercio al por mayor de materias primas agropecuarias y animales vivos" },
  { code: "4631", name: "4631 - Comercio al por mayor de productos alimenticios" },
  { code: "4632", name: "4632 - Comercio al por mayor de bebidas y tabaco" },
  { code: "4641", name: "4641 - Comercio al por mayor de productos textiles, prendas de vestir y calzado" },
  { code: "4642", name: "4642 - Comercio al por mayor de electrodomésticos y artefactos del hogar" },
  { code: "4643", name: "4643 - Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador" },
  { code: "4644", name: "4644 - Comercio al por mayor de artículos de papelería, libros, periódicos y útiles de oficina" },
  { code: "4649", name: "4649 - Comercio al por mayor de otros utensilios domésticos n.c.p." },
  { code: "4651", name: "4651 - Comercio al por mayor de computadores, equipos periféricos y programas de informática" },
  { code: "4652", name: "4652 - Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones" },
  { code: "4653", name: "4653 - Comercio al por mayor de maquinaria y equipo agropecuarios" },
  { code: "4659", name: "4659 - Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p." },
  { code: "4661", name: "4661 - Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos" },
  { code: "4662", name: "4662 - Comercio al por mayor de metales y minerales metalíferos" },
  { code: "4663", name: "4663 - Comercio al por mayor de materiales de construcción, ferretería, fontanería y calefacción" },
  { code: "4664", name: "4664 - Comercio al por mayor de productos químicos básicos, cauchos y plásticos primarios" },
  { code: "4665", name: "4665 - Comercio al por mayor de desperdicios, desechos y chatarra" },
  { code: "4669", name: "4669 - Comercio al por mayor de otros productos especializados n.c.p." },
  { code: "4690", name: "4690 - Comercio al por mayor no especializado" },
  { code: "4711", name: "4711 - Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco" },
  { code: "4719", name: "4719 - Comercio al por menor en otros establecimientos no especializados (tiendas departamentales)" },
  { code: "4721", name: "4721 - Comercio al por menor de alimentos en establecimientos especializados" },
  { code: "4722", name: "4722 - Comercio al por menor de bebidas y tabaco en establecimientos especializados" },
  { code: "4731", name: "4731 - Comercio al por menor de combustible para vehículos automotores" },
  { code: "4732", name: "4732 - Comercio al por menor de lubricantes, aditivos y productos de limpieza para vehículos" },
  { code: "4741", name: "4741 - Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones" },
  { code: "4742", name: "4742 - Comercio al por menor de equipos de sonido y de video en establecimientos especializados" },
  { code: "4751", name: "4751 - Comercio al por menor de productos textiles en establecimientos especializados" },
  { code: "4752", name: "4752 - Comercio al por menor de artículos de ferretería, pinturas y vidrio en establecimientos especializados" },
  { code: "4753", name: "4753 - Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos" },
  { code: "4754", name: "4754 - Comercio al por menor de electrodomésticos y muebles para el hogar" },
  { code: "4755", name: "4755 - Comercio al por menor de artículos y utensilios de uso doméstico" },
  { code: "4759", name: "4759 - Comercio al por menor de otros artículos para el hogar en establecimientos especializados" },
  { code: "4761", name: "4761 - Comercio al por menor de libros, periódicos, materiales y artículos de papelería" },
  { code: "4762", name: "4762 - Comercio al por menor de grabaciones de música y de video en establecimientos especializados" },
  { code: "4769", name: "4769 - Comercio al por menor de artículos deportivos y juguetes en establecimientos especializados" },
  { code: "4771", name: "4771 - Comercio al por menor de prendas de vestir y sus accesorios en establecimientos especializados" },
  { code: "4772", name: "4772 - Comercio al por menor de todo tipo de calzado y artículos de cuero" },
  { code: "4773", name: "4773 - Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador" },
  { code: "4774", name: "4774 - Comercio al por menor de otros productos nuevos en establecimientos especializados" },
  { code: "4775", name: "4775 - Comercio al por menor de artículos de segunda mano" },
  { code: "4781", name: "4781 - Comercio al por menor de alimentos, bebidas y tabaco en puestos de venta o mercados" },
  { code: "4782", name: "4782 - Comercio al por menor de productos textiles, prendas de vestir y calzado en puestos de venta o mercados" },
  { code: "4789", name: "4789 - Comercio al por menor de otros productos en puestos de venta o mercados" },
  { code: "4791", name: "4791 - Comercio al por menor realizado a través de internet o por correo" },
  { code: "4792", name: "4792 - Comercio al por menor realizado a través de casas de venta o venta directa" },
  { code: "4799", name: "4799 - Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados" },

  // SECCIÓN H - TRANSPORTE Y ALMACENAMIENTO
  { code: "4911", name: "4911 - Transporte férreo de pasajeros" },
  { code: "4912", name: "4912 - Transporte férreo de carga" },
  { code: "4921", name: "4921 - Transporte de pasajeros" },
  { code: "4922", name: "4922 - Transporte mixto" },
  { code: "4923", name: "4923 - Transporte de carga por carretera" },
  { code: "4930", name: "4930 - Transporte por tuberías" },
  { code: "5011", name: "5011 - Transporte marítimo y de cabotaje de pasajeros" },
  { code: "5012", name: "5012 - Transporte marítimo y de cabotaje de carga" },
  { code: "5021", name: "5021 - Transporte fluvial de pasajeros" },
  { code: "5022", name: "5022 - Transporte fluvial de carga" },
  { code: "5111", name: "5111 - Transporte aéreo nacional de pasajeros" },
  { code: "5112", name: "5112 - Transporte aéreo internacional de pasajeros" },
  { code: "5121", name: "5121 - Transporte aéreo nacional de carga" },
  { code: "5122", name: "5122 - Transporte aéreo internacional de carga" },
  { code: "5210", name: "5210 - Almacenamiento y depósito" },
  { code: "5221", name: "5221 - Actividades de estaciones, vías y servicios complementarios para el transporte terrestre" },
  { code: "5222", name: "5222 - Actividades de puertos y servicios complementarios para el transporte acuático" },
  { code: "5223", name: "5223 - Actividades de aeropuertos y servicios complementarios para el transporte aéreo" },
  { code: "5224", name: "5224 - Manipulación de carga" },
  { code: "5229", name: "5229 - Otras actividades complementarias al transporte" },
  { code: "5310", name: "5310 - Actividades postales nacionales" },
  { code: "5320", name: "5320 - Actividades de mensajería" },

  // SECCIÓN I - ALOJAMIENTO Y SERVICIOS DE COMIDA
  { code: "5511", name: "5511 - Alojamiento en hoteles" },
  { code: "5512", name: "5512 - Alojamiento en aparthoteles" },
  { code: "5513", name: "5513 - Alojamiento en centros vacacionales" },
  { code: "5514", name: "5514 - Alojamiento rural" },
  { code: "5519", name: "5519 - Otros tipos de alojamiento para visitantes" },
  { code: "5520", name: "5520 - Actividades de zonas de camping y parques para vehículos de recreo" },
  { code: "5590", name: "5590 - Otros tipos de alojamiento n.c.p." },
  { code: "5611", name: "5611 - Expendio a la mesa de comidas preparadas" },
  { code: "5612", name: "5612 - Expendio por autoservicio de comidas preparadas" },
  { code: "5613", name: "5613 - Expendio de comidas preparadas en cafeterías" },
  { code: "5619", name: "5619 - Otros tipos de expendio de comidas preparadas n.c.p." },
  { code: "5621", name: "5621 - Catering para eventos" },
  { code: "5629", name: "5629 - Otros servicios de alimentación" },
  { code: "5630", name: "5630 - Expendio de bebidas alcohólicas para el consumo dentro del establecimiento" },

  // SECCIÓN J - INFORMACIÓN Y COMUNICACIONES
  { code: "5811", name: "5811 - Edición de libros" },
  { code: "5812", name: "5812 - Edición de directorios y listas de correo" },
  { code: "5813", name: "5813 - Edición de periódicos, revistas y publicaciones periódicas" },
  { code: "5819", name: "5819 - Otras actividades de edición" },
  { code: "5820", name: "5820 - Edición de programas de informática (software)" },
  { code: "5911", name: "5911 - Actividades de producción de películas cinematográficas, videos y programas de televisión" },
  { code: "5912", name: "5912 - Actividades de posproducción de películas cinematográficas, videos y programas de televisión" },
  { code: "5913", name: "5913 - Actividades de distribución de películas cinematográficas, videos y programas de televisión" },
  { code: "5914", name: "5914 - Actividades de exhibición de películas cinematográficas y videos" },
  { code: "5920", name: "5920 - Actividades de grabación de sonido y edición de música" },
  { code: "6010", name: "6010 - Actividades de programación y transmisión en el servicio de radiodifusión sonora" },
  { code: "6020", name: "6020 - Actividades de programación y transmisión de televisión" },
  { code: "6110", name: "6110 - Actividades de telecomunicaciones alámbricas" },
  { code: "6120", name: "6120 - Actividades de telecomunicaciones inalámbricas" },
  { code: "6130", name: "6130 - Actividades de telecomunicación por satélite" },
  { code: "6190", name: "6190 - Otras actividades de telecomunicaciones" },
  { code: "6201", name: "6201 - Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)" },
  { code: "6202", name: "6202 - Actividades de consultoría informática y administración de instalaciones informáticas" },
  { code: "6209", name: "6209 - Otras actividades de tecnologías de información y servicios informáticos" },
  { code: "6311", name: "6311 - Procesamiento de datos, alojamiento (hosting) y actividades conexas" },
  { code: "6312", name: "6312 - Portales web" },
  { code: "6391", name: "6391 - Actividades de agencias de noticias" },
  { code: "6399", name: "6399 - Otras actividades de servicios de información n.c.p." },

  // SECCIÓN K - ACTIVIDADES FINANCIERAS Y DE SEGUROS
  { code: "6411", name: "6411 - Banco Central" },
  { code: "6412", name: "6412 - Bancos comerciales" },
  { code: "6421", name: "6421 - Actividades de las sociedades de cartera (holding)" },
  { code: "6422", name: "6422 - Fideicomisos, fondos y entidades financieras similares" },
  { code: "6431", name: "6431 - Leasing financiero" },
  { code: "6432", name: "6432 - Factoring" },
  { code: "6491", name: "6491 - Leasing financiero y arrendamiento de bienes intangibles" },
  { code: "6492", name: "6492 - Otras actividades de concesión de crédito" },
  { code: "6493", name: "6493 - Actividades de las casas de cambio" },
  { code: "6494", name: "6494 - Otras actividades de distribución de fondos o intermediación financiera" },
  { code: "6495", name: "6495 - Instituciones financieras de fomento" },
  { code: "6499", name: "6499 - Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p." },
  { code: "6511", name: "6511 - Seguros generales" },
  { code: "6512", name: "6512 - Seguros de vida" },
  { code: "6513", name: "6513 - Reaseguros" },
  { code: "6514", name: "6514 - Capitalización" },
  { code: "6521", name: "6521 - Servicios de seguros de salud" },
  { code: "6522", name: "6522 - Servicios de riesgos laborales" },
  { code: "6531", name: "6531 - Régimen de prima media con prestación definida (RPM)" },
  { code: "6532", name: "6532 - Régimen de ahorro individual con solidaridad (RAIS)" },
  { code: "6611", name: "6611 - Administración de mercados financieros" },
  { code: "6612", name: "6612 - Corretaje de valores y de contratos de productos básicos" },
  { code: "6613", name: "6613 - Otras actividades relacionadas con los mercados financieros" },
  { code: "6614", name: "6614 - Actividades de las sociedades de intermediación cambiaria y de servicios financieros especiales" },
  { code: "6615", name: "6615 - Actividades de los profesionales de compra y venta de divisas" },
  { code: "6619", name: "6619 - Otras actividades auxiliares de las actividades de servicios financieros n.c.p." },
  { code: "6621", name: "6621 - Evaluación de riesgos y daños" },
  { code: "6622", name: "6622 - Actividades de agentes y corredores de seguros" },
  { code: "6629", name: "6629 - Otras actividades auxiliares de las actividades de seguros y fondos de pensiones" },
  { code: "6630", name: "6630 - Actividades de administración de fondos" },

  // SECCIÓN L - ACTIVIDADES INMOBILIARIAS
  { code: "6810", name: "6810 - Actividades inmobiliarias realizadas con bienes propios o arrendados" },
  { code: "6820", name: "6820 - Actividades inmobiliarias realizadas a cambio de una retribución o por contrata" },

  // SECCIÓN M - ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS
  { code: "6910", name: "6910 - Actividades jurídicas" },
  { code: "6920", name: "6920 - Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría fiscal" },
  { code: "7010", name: "7010 - Actividades de las oficinas centrales (sede principal)" },
  { code: "7020", name: "7020 - Actividades de consultoría de gestión" },
  { code: "7110", name: "7110 - Actividades de arquitectura e ingeniería y actividades conexas de consultoría técnica" },
  { code: "7120", name: "7120 - Ensayos y análisis técnicos" },
  { code: "7210", name: "7210 - Investigaciones y desarrollos experimentales en el campo de las ciencias naturales y la ingeniería" },
  { code: "7220", name: "7220 - Investigaciones y desarrollos experimentales en el campo de las ciencias sociales y las humanidades" },
  { code: "7310", name: "7310 - Publicidad" },
  { code: "7320", name: "7320 - Estudio de mercado y realización de encuestas de opinión pública" },
  { code: "7410", name: "7410 - Actividades especializadas de diseño" },
  { code: "7420", name: "7420 - Actividades de fotografía" },
  { code: "7490", name: "7490 - Otras actividades profesionales, científicas y técnicas n.c.p." },
  { code: "7500", name: "7500 - Actividades veterinarias" },

  // SECCIÓN N - ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO
  { code: "7710", name: "7710 - Alquiler y arrendamiento de vehículos automotores" },
  { code: "7721", name: "7721 - Alquiler y arrendamiento de equipo recreativo y deportivo" },
  { code: "7722", name: "7722 - Alquiler de cintas de video y discos" },
  { code: "7729", name: "7729 - Alquiler y arrendamiento de otros efectos personales y enseres domésticos" },
  { code: "7730", name: "7730 - Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles" },
  { code: "7740", name: "7740 - Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor" },
  { code: "7810", name: "7810 - Actividades de agencias de empleo" },
  { code: "7820", name: "7820 - Actividades de agencias de empleo temporal" },
  { code: "7830", name: "7830 - Otras actividades de provisión de recursos humanos" },
  { code: "7911", name: "7911 - Actividades de las agencias de viajes" },
  { code: "7912", name: "7912 - Actividades de los operadores turísticos" },
  { code: "7990", name: "7990 - Otros servicios de reserva y actividades relacionadas" },
  { code: "8010", name: "8010 - Actividades de seguridad privada" },
  { code: "8020", name: "8020 - Actividades de servicios de sistemas de seguridad" },
  { code: "8030", name: "8030 - Actividades de detectives e investigación privada" },
  { code: "8110", name: "8110 - Actividades combinadas de apoyo a instalaciones" },
  { code: "8121", name: "8121 - Limpieza general de edificios" },
  { code: "8129", name: "8129 - Otras actividades de limpieza de edificios e instalaciones industriales" },
  { code: "8130", name: "8130 - Actividades de paisajismo y servicios de mantenimiento conexos" },
  { code: "8211", name: "8211 - Actividades combinadas de servicios administrativos de oficina" },
  { code: "8219", name: "8219 - Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficinas" },
  { code: "8220", name: "8220 - Actividades de centros de llamadas (Call center)" },
  { code: "8230", name: "8230 - Organización de convenciones y eventos comerciales" },
  { code: "8291", name: "8291 - Actividades de agencias de cobro y oficinas de crédito" },
  { code: "8292", name: "8292 - Actividades de envase y empaque" },
  { code: "8299", name: "8299 - Otras actividades de servicio de apoyo a las empresas n.c.p." },

  // SECCIÓN O - ADMINISTRACIÓN PÚBLICA Y DEFENSA
  { code: "8411", name: "8411 - Actividades de la administración pública en general" },
  { code: "8412", name: "8412 - Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales" },
  { code: "8413", name: "8413 - Regulación y facilitación de la actividad económica" },
  { code: "8414", name: "8414 - Actividades de relaciones exteriores" },
  { code: "8421", name: "8421 - Asuntos de defensa" },
  { code: "8422", name: "8422 - Actividades de mantenimiento del orden público y de seguridad" },
  { code: "8423", name: "8423 - Actividades de administración de justicia" },
  { code: "8430", name: "8430 - Actividades de planes de seguridad social de afiliación obligatoria" },

  // SECCIÓN P - EDUCACIÓN
  { code: "8511", name: "8511 - Educación de primera infancia" },
  { code: "8512", name: "8512 - Educación preescolar" },
  { code: "8513", name: "8513 - Educación básica primaria" },
  { code: "8521", name: "8521 - Educación básica secundaria" },
  { code: "8522", name: "8522 - Educación media académica" },
  { code: "8523", name: "8523 - Educación media técnica y de formación laboral" },
  { code: "8530", name: "8530 - Establecimientos que prestan educación técnica profesional, tecnológica y universitaria" },
  { code: "8541", name: "8541 - Educación deportiva y recreativa" },
  { code: "8542", name: "8542 - Educación cultural" },
  { code: "8549", name: "8549 - Otros tipos de educación n.c.p." },
  { code: "8550", name: "8550 - Actividades de apoyo a la educación" },

  // SECCIÓN Q - ATENCIÓN DE LA SALUD HUMANA Y ASISTENCIA SOCIAL
  { code: "8610", name: "8610 - Actividades de hospitales y clínicas, con internación" },
  { code: "8621", name: "8621 - Actividades de la práctica médica, sin internación" },
  { code: "8622", name: "8622 - Actividades de la práctica odontológica" },
  { code: "8691", name: "8691 - Actividades de apoyo diagnóstico" },
  { code: "8692", name: "8692 - Actividades de apoyo terapéutico" },
  { code: "8699", name: "8699 - Otras actividades de atención de la salud humana" },
  { code: "8710", name: "8710 - Actividades de atención residential con cuidado médico paramédico" },
  { code: "8720", name: "8720 - Actividades de atención residencial para el retraso mental, la salud mental y la adicción" },
  { code: "8730", name: "8730 - Actividades de atención residencial para personas de la tercera edad y personas con discapacidad" },
  { code: "8790", name: "8790 - Otras actividades de atención residencial" },
  { code: "8810", name: "8810 - Actividades de asistencia social sin alojamiento para personas de la tercera edad y personas con discapacidad" },
  { code: "8890", name: "8890 - Otras actividades de asistencia social sin alojamiento" },

  // SECCIÓN R - ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN
  { code: "9001", name: "9001 - Creación teatral" },
  { code: "9002", name: "9002 - Creación musical" },
  { code: "9003", name: "9003 - Creación literaria" },
  { code: "9004", name: "9004 - Creación plástica y visual" },
  { code: "9005", name: "9005 - Artes escénicas" },
  { code: "9006", name: "9006 - Actividades teatrales y musicales conexas" },
  { code: "9007", name: "9007 - Actividades de espectáculos en vivo" },
  { code: "9008", name: "9008 - Otras actividades de creación artística y de entretenimiento" },
  { code: "9101", name: "9101 - Actividades de bibliotecas y archivos" },
  { code: "9102", name: "9102 - Actividades de museos, conservación de lugares y edificios históricos" },
  { code: "9103", name: "9103 - Actividades de jardines botánicos, zoológicos y reservas naturales" },
  { code: "9200", name: "9200 - Actividades de juegos de azar y apuestas" },
  { code: "9311", name: "9311 - Gestión de instalaciones deportivas" },
  { code: "9312", name: "9312 - Actividades de clubes deportivos" },
  { code: "9319", name: "9319 - Otras actividades deportivas" },
  { code: "9321", name: "9321 - Actividades de parques de atracciones y parques temáticos" },
  { code: "9329", name: "9329 - Otras actividades de recreación y esparcimiento n.c.p." },

  // SECCIÓN S - OTRAS ACTIVIDADES DE SERVICIOS
  { code: "9411", name: "9411 - Actividades de asociaciones empresariales y de empleadores" },
  { code: "9412", name: "9412 - Actividades de asociaciones profesionales" },
  { code: "9420", name: "9420 - Actividades de sindicatos de trabajadores" },
  { code: "9491", name: "9491 - Actividades de organizaciones religiosas" },
  { code: "9492", name: "9492 - Actividades de organizaciones políticas" },
  { code: "9499", name: "9499 - Actividades de otras asociaciones n.c.p." },
  { code: "9511", name: "9511 - Mantenimiento y reparación de computadores y equipo periférico" },
  { code: "9512", name: "9512 - Mantenimiento y reparación de equipos de comunicación" },
  { code: "9521", name: "9521 - Mantenimiento y reparación de aparatos electrónicos de consumo" },
  { code: "9522", name: "9522 - Mantenimiento y reparación de aparatos de uso doméstico y equipo para hogar" },
  { code: "9523", name: "9523 - Reparación de calzado y artículos de cuero" },
  { code: "9524", name: "9524 - Reparación de muebles y accesorios para el hogar" },
  { code: "9529", name: "9529 - Mantenimiento y reparación de otros efectos personales y enseres domésticos" },
  { code: "9601", name: "9601 - Lavado y limpieza de productos textiles y de piel" },
  { code: "9602", name: "9602 - Peluquería y otros tratamientos de belleza" },
  { code: "9603", name: "9603 - Pompas fúnebres y actividades relacionadas" },
  { code: "9609", name: "9609 - Otras actividades de servicios personales n.c.p." },

  // SECCIÓN T - ACTIVIDADES DE HOGARES INDIVIDUALES
  { code: "9700", name: "9700 - Actividades de los hogares individuales como empleadores de personal doméstico" },
  { code: "9810", name: "9810 - Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio" },
  { code: "9820", name: "9820 - Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio" },

  // SECCIÓN U - ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES
  { code: "9900", name: "9900 - Actividades de organizaciones y órganos extraterritoriales" }
];
